### ISSUE TITLE
Image is saving without background, but displaying in UI with background.

### ISSUE THREAD

**Issue by iredmedia** [Jcd1230/rembg-comfyui-node#1]
I'm not sure if I'm doing something wrong, my hope was to be able to remove the background, then photobash it with another background. Your example shows it working so I'm wondering if I've done something wrong somewhere?

![image](https://github.com/Jcd1230/rembg-comfyui-node/assets/584038/5b1311d2-bf20-42c9-8671-09ef6c85883c)

**Comment by Jcd1230** [comment]
Hi!
The node still works on my machine, just pulled the latest version of ComfyUI as well.

However, since I made this repository, the WAS node suite added their own version of rembg, which is the lower node in your screenshot - "Image RemBG (Remove Background)", whereas this repository adds the "Image Remove Background (rembg)" node.

I would recommend using the WAS version going forward, since it will certainly get better support this repository with just me maintaining it (unfortunately); From looking at the code they are very very similar in functionality so you shouldn't be missing out on anything. And as long as you install the GPU version of rembg manually it should be the same speed.

![image](https://github.com/Jcd1230/rembg-comfyui-node/assets/604001/c4d5b4e7-f8b1-4f86-a4f8-96b9995ecc3e)

As you can see though, both nodes are working for me.

If you can provide logs from your ComfyUI server while this is happening that might shed light on the issue, otherwise I don't think there's much I can do.

Thanks for the feedback though!

**Comment by pauloeli** [comment]
Is there a good place to find workflows to use with this template? I'm having trouble setting it up.
